[package]
name = "mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true
turbomcp = { version = "2.3.6", features = ["http"] }
